<?php

/**
 * @file
 * This is the module to create a games.
 */

/**
 * Implements hook_preprocess_HOOK().
 */
function games_preprocess_page(&$variables) {
  if (\Drupal::routeMatch()->getRouteName() === 'entity.node.canonical') {
    /** @var \Drupal\node\NodeInterface $node */
    $node = \Drupal::routeMatch()->getParameter('node');
    if ($node) {
      $variables['#attached']['drupalSettings']['nodeId'] = $node->id();
    }
  }
}
